version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ 기본 포트
      - "15672:15672"  # Management UI 포트
    environment:
      - RABBITMQ_DEFAULT_USER=guest     # 기본 사용자명
      - RABBITMQ_DEFAULT_PASS=guest     # 기본 비밀번호
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # 데이터 지속성을 위한 볼륨
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - rabbitmq_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
  rabbitmq_logs:

networks:
  rabbitmq_network:
    driver: bridge
